# Site settings
title: SCALEY | HEAT EP
email: JP@SCALEYMADE.com
description: SCALEY IS LURKING THE DEEP CORNERS OF THE INTERNET EXPERIMENTING WITH EXTREME HIGH-ENERGY BASS MUSIC. SINCE HIS LAST REMIX OF "WAITING" WAS RELEASED HE HAS RECEIVED SUPPORT FROM SOME OF THE BIGGEST NAMES IN THE ONLINE BASS MUSIC COMMUNITY. HE IS CONTINUING TO STIR THE INTERNET POT WITH WILD TRACK RELEASES THAT MOST CAN ONLY DESCRIBE AS "HYBRID". NOW HE KNOWS HOW TO DRIVE PEOPLE TO BRINK OF INSANITY, AND HE IS HITTING THE SCENE WITH A VENGEANCE...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://SCALEYMADE.com" # the base hostname & protocol for your site
twitter_username: SCALEYMADE

# Build settings
markdown: kramdown
permalink: pretty
